version: "3"

services:
  database:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=shopping_history
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./.mongo-volume:/data/db
    ports:
      - "27017:27017"